cmake_minimum_required(VERSION 3.21)
foreach(name IN ITEMS BRIDGE_TEST_EXE PLUGIN_FILE LEGACY_PLUGIN_FILE STAGING_DIR)
    if(NOT DEFINED ${name})
        message(FATAL_ERROR "${name} is required")
    endif()
endforeach()
set(stage "${STAGING_DIR}/中文/installed-plugin-identity-and-generation-12345678901234567890")
file(MAKE_DIRECTORY "${stage}")
get_filename_component(plugin_name "${PLUGIN_FILE}" NAME)
set(staged_plugin "${stage}/${plugin_name}")
file(COPY_FILE "${PLUGIN_FILE}" "${staged_plugin}")
string(LENGTH "${staged_plugin}" staged_length)
if(staged_length LESS 248)
    message(FATAL_ERROR "long-path regression fixture is too short: ${staged_length}")
endif()
execute_process(COMMAND "${BRIDGE_TEST_EXE}" "${staged_plugin}"
    "${LEGACY_PLUGIN_FILE}" RESULT_VARIABLE result)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "installed long-path native bridge failed: ${result}")
endif()
